set -g status off
set -g mouse on
set -s escape-time 10

# Reload config (Ctrl+b r)
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Show command prompt (Alt+p)
bind -n M-p command-prompt

# Split panes (Alt+e/o)
bind -n M-e split-window -h
bind -n M-o split-window -v
# Toggle zoom panel (Alt+z)
bind -n M-z resize-pane -Z
# Kill pane (Alt+x)
bind -n M-x kill-pane

# Move around panes (Alt+arrows)
bind -n M-Up select-pane -U
bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Right select-pane -R

# Move around panes (Alt+i/j/k/l)
# Safe if Alt+arrows is not available
bind -n M-i select-pane -U
bind -n M-j select-pane -L
bind -n M-k select-pane -D
bind -n M-l select-pane -R

# Resize panes (Alt+Shift+i/j/k/l)
bind -n M-I resize-pane -U 2
bind -n M-L resize-pane -R 2
bind -n M-K resize-pane -D 2
bind -n M-J resize-pane -L 2
