set -g status off
set -g mouse on

# Reload config (Ctrl+b r)
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Show command prompt (Alt+p)
bind -n M-p command-prompt

# Split panes (Alt+e/o)
bind -n M-e split-window -h
bind -n M-o split-window -v
# Toggle zoom panel (Alt+z)
bind -n M-z resize-pane -Z
# Kill pane (Alt+x)
bind -n M-x kill-pane

# Move around panes (Alt+arrows)
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L

# Resize panes (Alt+i/j/k/l)
bind -n M-i resize-pane -U
bind -n M-j resize-pane -D
bind -n M-k resize-pane -L
bind -n M-l resize-pane -R
